
const data=JSON.parse(document.getElementById('dashboard-data').textContent);
let metric='MAU', viewMode='abs', selectedApps=['小宇宙'];
let sortState={key:'rank',dir:1};
const colors=['#bd3c31','#155f7b','#3f7b4c','#bd8426','#6c4d9a','#d06931','#248b8b','#7e5632','#9b2f55','#355c9a'];
const $=id=>document.getElementById(id);
const fmt=(x,d=1)=>x==null||Number.isNaN(x)?'—':Number(x).toLocaleString('zh-CN',{maximumFractionDigits:d,minimumFractionDigits:d});
const pct=x=>x==null?'—':`${x>0?'+':''}${Number(x).toFixed(1)}%`;
const esc=s=>String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
function niceTicks(min,max,count=5){ if(!isFinite(min)||!isFinite(max)) return [0,1]; if(min===max){min-=1;max+=1} const span=max-min, raw=span/(count-1), pow=Math.pow(10,Math.floor(Math.log10(raw))); const step=([1,2,2.5,5,10].find(m=>m*pow>=raw)||10)*pow; const start=Math.floor(min/step)*step,end=Math.ceil(max/step)*step; let out=[]; for(let v=start;v<=end+step*.5;v+=step) out.push(Math.abs(v)<1e-9?0:v); return out; }
function lineChart(canvas, series, opts={}){ const box=canvas.parentElement, dpr=window.devicePixelRatio||1, w=box.clientWidth, h=box.clientHeight; canvas.width=w*dpr; canvas.height=h*dpr; const ctx=canvas.getContext('2d'); ctx.setTransform(dpr,0,0,dpr,0,0); ctx.clearRect(0,0,w,h); const pad={l:72,r:24,t:24,b:42,...(opts.pad||{})}; const all=series.flatMap(s=>s.values).filter(v=>v!=null&&isFinite(v)); let min=opts.min??Math.min(...all), max=opts.max??Math.max(...all); if(!isFinite(min)||!isFinite(max)){min=0;max=1} const span=max-min||1; min=min-span*.10; max=max+span*.12; const ticks=niceTicks(min,max,5); min=Math.min(...ticks); max=Math.max(...ticks); const x=i=>pad.l+i*(w-pad.l-pad.r)/(data.months.length-1); const y=v=>h-pad.b-(v-min)/(max-min)*(h-pad.t-pad.b); ctx.font='12px Trebuchet MS, Microsoft YaHei'; ctx.textBaseline='middle'; ticks.forEach(t=>{ const yy=y(t); ctx.strokeStyle='rgba(120,100,80,.22)'; ctx.setLineDash([4,6]); ctx.beginPath(); ctx.moveTo(pad.l,yy); ctx.lineTo(w-pad.r,yy); ctx.stroke(); ctx.setLineDash([]); ctx.fillStyle='#5f554a'; ctx.textAlign='right'; ctx.fillText(fmt(t,t>=1000?0:1),pad.l-10,yy); }); ctx.strokeStyle='#a89782'; ctx.lineWidth=1.2; ctx.beginPath(); ctx.moveTo(pad.l,pad.t); ctx.lineTo(pad.l,h-pad.b); ctx.lineTo(w-pad.r,h-pad.b); ctx.stroke(); ctx.fillStyle='#5f554a'; ctx.textAlign='left'; ctx.textBaseline='top'; ctx.font='bold 12px Trebuchet MS, Microsoft YaHei'; ctx.fillText(opts.unit||'单位：万人',pad.l,pad.t-20); ctx.font='12px Trebuchet MS, Microsoft YaHei'; ctx.textBaseline='top'; data.months.forEach((m,i)=>{ if(i%4===0||i===data.months.length-1){ ctx.fillStyle='#6f665c'; ctx.textAlign='center'; ctx.fillText(m.slice(2),x(i),h-28); } }); series.forEach((s,si)=>{ ctx.strokeStyle=s.color||colors[si%colors.length]; ctx.lineWidth=3; ctx.beginPath(); s.values.forEach((v,i)=>{ if(v==null) return; const xx=x(i), yy=y(v); if(i===0) ctx.moveTo(xx,yy); else ctx.lineTo(xx,yy); }); ctx.stroke(); s.values.forEach((v,i)=>{ if(v==null) return; ctx.fillStyle=s.color||colors[si%colors.length]; ctx.beginPath(); ctx.arc(x(i),y(v),3.2,0,Math.PI*2); ctx.fill(); }); const last=s.values.at(-1); if(last!=null && opts.labels!==false){ ctx.fillStyle=s.color||colors[si%colors.length]; ctx.textAlign='left'; ctx.textBaseline='middle'; ctx.font='bold 12px Trebuchet MS, Microsoft YaHei'; ctx.fillText(s.name,w-pad.r+4,y(last)); } }); }
function init(){ $('dateRange').textContent=`${data.summary.month_start} → ${data.summary.month_end} · ${data.summary.app_count} Apps`; $('sourceLine').textContent=`数据源：${data.source.mauFile} / ${data.source.dauFile}`; $('insights').innerHTML=data.insights.map(x=>`<li>${x}</li>`).join(''); renderPicker(); }
function renderKPIs(){ const s=data.summary; const arr=[['行业MAU',`${fmt(s.latest_mau)}万`,`全周期 ${pct(s.mau_growth_total)}`],['行业DAU',`${fmt(s.latest_dau)}万`,`全周期 ${pct(s.dau_growth_total)}`],['DAU/MAU',`${fmt(s.latest_stickiness)}%`,'最新月粘性'],['增长最强',data.champion.app,`MAU ${pct(data.champion.mau_growth)}`]]; $('kpis').innerHTML=arr.map(x=>`<article class="card"><div class="kpi-label">${x[0]}</div><div class="kpi-value">${x[1]}</div><div class="kpi-sub">${x[2]}</div></article>`).join(''); }
function renderIndustry(){ lineChart($('mauCanvas'),[{name:'MAU',values:data.industry.map(d=>d.MAU),color:'#bd3c31'}],{unit:'单位：万人',labels:false,pad:{l:82,r:28,t:30,b:48}}); lineChart($('dauCanvas'),[{name:'DAU',values:data.industry.map(d=>d.DAU),color:'#155f7b'}],{unit:'单位：万人',labels:false,pad:{l:82,r:28,t:30,b:48}}); }
function productSeries(){ return selectedApps.map((app,i)=>{ const p=data.products.find(x=>x.app===app); let values=data.months.map(m=>p?.[metric]?.[m]??null); if(viewMode==='index'){ const base=values.find(v=>v&&v>0); values=values.map(v=>base&&v!=null?v/base*100:null); } return {name:app,values,color:colors[i%colors.length]}; }); }
function renderProduct(){ lineChart($('productCanvas'),productSeries(),{unit:viewMode==='index'?'指数（首月=100）':'单位：万人',pad:{r:110}}); }
function renderConcentration(){ lineChart($('concCanvas'),[{name:'Top1',values:data.concentration.map(d=>d.top1),color:'#bd3c31'},{name:'Top3',values:data.concentration.map(d=>d.top3),color:'#155f7b'},{name:'Top5',values:data.concentration.map(d=>d.top5),color:'#3f7b4c'}],{unit:'MAU份额 %',pad:{r:68}}); }
function renderTop(){ const rows=(metric==='MAU'?data.topMAU:data.topDAU).slice(0,10); $('topTitle').textContent=`最新 ${metric} 排名`; $('topList').innerHTML=rows.map((r,i)=>`<div class="rank-item"><span><b>#${i+1} ${esc(r.app)}</b><br>${esc(r.company||'')}</span><span><b>${fmt(metric==='MAU'?r.mau_last:r.dau_last)}万</b><br>份额 ${fmt(r.share)}%</span></div>`).join(''); }
function renderGrowth(){ const max=data.fastGrowers[0].mau_growth||1; $('growthPanel').innerHTML=`<div class="card" style="box-shadow:none;background:#ffffff;border-color:#e6e9ef"><div class="kpi-label">增长冠军</div><div class="kpi-value">${esc(data.champion.app)}</div><div class="kpi-sub">MAU ${fmt(data.champion.mau_first)}万 → ${fmt(data.champion.mau_last)}万，累计 ${pct(data.champion.mau_growth)}，排名 ${data.champion.mau_rank_start}→${data.champion.mau_rank_last}</div></div>`+data.fastGrowers.slice(0,8).map(r=>`<div class="barrow"><span>${esc(r.app)}</span><div class="bartrack"><div class="bar" style="width:${Math.min(100,(r.mau_growth||0)/max*100)}%"></div></div><span>${pct(r.mau_growth)}</span></div>`).join(''); }
function renderPicker(){ const q=($('pickerSearch').value||'').toLowerCase(); const rows=data.products.slice().sort((a,b)=>(b.mau_last||0)-(a.mau_last||0)).filter(p=>!q||p.app.toLowerCase().includes(q)||(p.company||'').toLowerCase().includes(q)).slice(0,50); $('productChecks').innerHTML=rows.map(p=>`<label><input type="checkbox" value="${esc(p.app)}" ${selectedApps.includes(p.app)?'checked':''}> ${esc(p.app)}</label>`).join(''); $('productChecks').querySelectorAll('input').forEach(cb=>cb.onchange=()=>{ if(cb.checked) selectedApps=Array.from(new Set([...selectedApps,cb.value])); else selectedApps=selectedApps.filter(x=>x!==cb.value); if(!selectedApps.length) selectedApps=['小宇宙']; renderProduct(); }); }
function renderTable(){ const q=$('searchBox').value.trim().toLowerCase(); let rows=data.products.filter(p=>!q||p.app.toLowerCase().includes(q)||(p.company||'').toLowerCase().includes(q)); const key=sortState.key; rows.sort((a,b)=>{ const va=key==='rank'?(metric==='MAU'?a.mau_rank_last:a.dau_rank_last):a[key], vb=key==='rank'?(metric==='MAU'?b.mau_rank_last:b.dau_rank_last):b[key]; if(typeof va==='string'||typeof vb==='string') return sortState.dir*String(va??'').localeCompare(String(vb??''),'zh-Hans-CN'); return sortState.dir*((va??Infinity)-(vb??Infinity)); }); const heads=[['rank','排名'],['app','App'],['company','公司'],[metric==='MAU'?'mau_last':'dau_last',`最新${metric}`],[metric==='MAU'?'mau_growth':'dau_growth','全周期增长'],[metric==='MAU'?'mau_mom':'dau_mom','最近环比'],[metric==='MAU'?'mau_rank_change':'dau_rank_change','排名变化'],['latest_stickiness','DAU/MAU'],['mau_last','最新MAU'],['dau_last','最新DAU']]; $('productTable').innerHTML=`<thead><tr>${heads.map(h=>`<th data-key="${h[0]}">${h[1]}</th>`).join('')}</tr></thead><tbody>${rows.map(p=>`<tr><td>${metric==='MAU'?(p.mau_rank_last||'—'):(p.dau_rank_last||'—')}</td><td><b>${esc(p.app)}</b></td><td>${esc(p.company||'')}</td><td>${fmt(metric==='MAU'?p.mau_last:p.dau_last)}万</td><td>${pct(metric==='MAU'?p.mau_growth:p.dau_growth)}</td><td>${pct(metric==='MAU'?p.mau_mom:p.dau_mom)}</td><td>${metric==='MAU'?(p.mau_rank_change??'—'):(p.dau_rank_change??'—')}</td><td>${fmt(p.latest_stickiness)}%</td><td>${fmt(p.mau_last)}万</td><td>${fmt(p.dau_last)}万</td></tr>`).join('')}</tbody>`; $('productTable').querySelectorAll('th').forEach(th=>th.onclick=()=>{ const k=th.dataset.key; if(sortState.key===k) sortState.dir*=-1; else sortState={key:k,dir:k==='rank'?1:-1}; renderTable(); }); }
function renderAll(){ renderKPIs(); renderIndustry(); renderProduct(); renderConcentration(); renderTop(); renderGrowth(); renderTable(); }
document.querySelectorAll('.metricBtn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.metricBtn').forEach(x=>x.classList.remove('active')); b.classList.add('active'); metric=b.dataset.metric; renderTop(); renderProduct(); renderTable(); });
document.querySelectorAll('.viewBtn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.viewBtn').forEach(x=>x.classList.remove('active')); b.classList.add('active'); viewMode=b.dataset.view; renderProduct(); });
$('onlyXiaoyuzhou').onclick=()=>{ selectedApps=['小宇宙']; renderPicker(); renderProduct(); }; $('pickerSearch').oninput=renderPicker; $('searchBox').oninput=renderTable; window.onresize=()=>{ clearTimeout(window.__r); window.__r=setTimeout(renderAll,150); };
init(); renderAll();
